### PR TITLE
add 2.4.1 items support

### PR DESCRIPTION
**Pull request by VennieSo**
Hi Raylehnhoff, 

I've added 2.4.1 item updates, hope this is useful. I certainly found your tool to be very much so.
Todo: update patch notice to offer season/non-season migration again.

Cheers,
Vennie

### CODE REVIEW

**Comment by Raylehnhoff** [comment]
Hey, thanks. This is actually super helpful. I've been working a lot lately and haven't really had time for my pet projects. I'll need to setup the migration before I can merge this PR, though.

**Comment by VennieSo** [comment]
FYI I had to force push amended commit messages to keep my email address private, so timeline's a bit off. Hope that doesn't cause you problems.

**Comment by Raylehnhoff** [comment]
No problem, I'm going to review this tomorrow (5/30) and get it merged in. Thanks again for taking the time to do this.

**Comment by Raylehnhoff** [comment]
@vennieso -- I pushed these changes to the HICTY-Test site, along with the changes necessary to do the migration. Can you please check it out to make sure it's working as expected? I tested against my 2.4 data, but I like to get a few other verifications before I push the updates out.

**Be sure to backup your HICTY settings prior to visiting.**

**Comment by VennieSo** [comment]
@Raylehnhoff where can I find the HICTY-Test site?

**Comment by Raylehnhoff** [comment]
@vennieso http://raylehnhoff.github.io/HICTY-Test

**Comment by VennieSo** [comment]
@Raylehnhoff looks good on my 2.4 data as well!

**Comment by Raylehnhoff** [comment]
I didn't merge this directly, but used parts of it. Thanks for your help on this, and sorry for the extreme delay.

**Pull request closed without merging**
